name: hear_me_safe
description: "Voice-activated personal safety app that alerts contacts and captures evidence when you need help"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  android_intent_plus: ^5.2.0
  flutter:
    sdk: flutter
  flutter_background: ^1.3.0+1
  flutter_localizations:
    sdk: flutter
  flutter_sound: ^9.16.3
  fluttertoast: ^8.2.8
  geolocator: ^13.0.1
  http: ^1.2.2
  intl: ^0.19.0
  logger: ^2.4.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.2
  vibration: ^2.0.1
  web_socket_channel: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.20

flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/icon.jpg" # Replace with your icon path

flutter_native_splash:
  color: "#ffffff" # Background color of the splash screen
  image: assets/images/splashscreen.jpg # Path to your splash image
  android: true
  ios: false
  android_gravity: fill

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
